### ISSUE TITLE
pip3 install pyqt5 fails on aarch64

### ISSUE THREAD

**Issue by bhlevca** [baoboa/pyqt5#71]
**Environment :

    OS: [debian aarch64]
    Python [ 3.7.3]
    PyQt5 [5.16]

Describe the bug or Expected behaviour ,

command pip3 install pyqt5 fails

Additional context and Screenshots

pip3 install pyqt5
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyqt5
  Using cached https://files.pythonhosted.org/packages/3b/27/fd81188a35f37be9b3b4c2db1654d9439d1418823916fe702ac3658c9c41/PyQt5-5.15.6.tar.gz
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-7g0eq6ep/pyqt5/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-7g0eq6ep/pyqt5/

```A clear and concise description of what the bug is.

Aarch64  packages which have pip dependencies on pyqt5 fail.

I installed pyqt5 with apt and then I removed pyqt5 from the list of required packages so that pip3 does not crash at build time.
However, the solution I proposed above for the aarch64 packages that have a pyqt5 dependency with pip is a temporary hack.

The real solution is to add PyQt5-5.15.6-cp36-abi3-manylinux1_aarch64.whl at https://pypi.org/project/PyQt5/#files

**Comment by AdityaShrivastava03** [comment]
Try  $sudo apt-get install python3-pyqt5
this command works for me
